# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orderbook_pb2 as orderbook__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orderbook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderBookStreamingStub(object):
    """Service for streaming real-time order book data.
    L2 provides aggregated price levels (px, total_sz, order_count).
    L4 provides individual order details (user, trigger info, timestamps).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamL2Book = channel.unary_stream(
                '/hyperliquid.OrderBookStreaming/StreamL2Book',
                request_serializer=orderbook__pb2.L2BookRequest.SerializeToString,
                response_deserializer=orderbook__pb2.L2BookUpdate.FromString,
                _registered_method=True)
        self.StreamL4Book = channel.unary_stream(
                '/hyperliquid.OrderBookStreaming/StreamL4Book',
                request_serializer=orderbook__pb2.L4BookRequest.SerializeToString,
                response_deserializer=orderbook__pb2.L4BookUpdate.FromString,
                _registered_method=True)


class OrderBookStreamingServicer(object):
    """Service for streaming real-time order book data.
    L2 provides aggregated price levels (px, total_sz, order_count).
    L4 provides individual order details (user, trigger info, timestamps).
    """

    def StreamL2Book(self, request, context):
        """Subscribe to L2 aggregated book updates for a coin.
        Sends a full L2 snapshot after each block is processed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamL4Book(self, request, context):
        """Subscribe to L4 full order book for a coin.
        Sends an initial L4 snapshot, then incremental diffs per block.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamL2Book': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamL2Book,
                    request_deserializer=orderbook__pb2.L2BookRequest.FromString,
                    response_serializer=orderbook__pb2.L2BookUpdate.SerializeToString,
            ),
            'StreamL4Book': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamL4Book,
                    request_deserializer=orderbook__pb2.L4BookRequest.FromString,
                    response_serializer=orderbook__pb2.L4BookUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperliquid.OrderBookStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperliquid.OrderBookStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookStreaming(object):
    """Service for streaming real-time order book data.
    L2 provides aggregated price levels (px, total_sz, order_count).
    L4 provides individual order details (user, trigger info, timestamps).
    """

    @staticmethod
    def StreamL2Book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid.OrderBookStreaming/StreamL2Book',
            orderbook__pb2.L2BookRequest.SerializeToString,
            orderbook__pb2.L2BookUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamL4Book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid.OrderBookStreaming/StreamL4Book',
            orderbook__pb2.L4BookRequest.SerializeToString,
            orderbook__pb2.L4BookUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
