# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamData = channel.stream_stream(
                '/hyperliquid.Streaming/StreamData',
                request_serializer=streaming__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=streaming__pb2.SubscribeUpdate.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/hyperliquid.Streaming/Ping',
                request_serializer=streaming__pb2.PingRequest.SerializeToString,
                response_deserializer=streaming__pb2.PingResponse.FromString,
                _registered_method=True)


class StreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamData(self, request_iterator, context):
        """Bi-directional streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=streaming__pb2.SubscribeRequest.FromString,
                    response_serializer=streaming__pb2.SubscribeUpdate.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=streaming__pb2.PingRequest.FromString,
                    response_serializer=streaming__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperliquid.Streaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperliquid.Streaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Streaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hyperliquid.Streaming/StreamData',
            streaming__pb2.SubscribeRequest.SerializeToString,
            streaming__pb2.SubscribeUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperliquid.Streaming/Ping',
            streaming__pb2.PingRequest.SerializeToString,
            streaming__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BlockStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBlocks = channel.unary_stream(
                '/hyperliquid.BlockStreaming/StreamBlocks',
                request_serializer=streaming__pb2.Timestamp.SerializeToString,
                response_deserializer=streaming__pb2.Block.FromString,
                _registered_method=True)


class BlockStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamBlocks(self, request, context):
        """Stream replica_cmds (raw blocks)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBlocks,
                    request_deserializer=streaming__pb2.Timestamp.FromString,
                    response_serializer=streaming__pb2.Block.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperliquid.BlockStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperliquid.BlockStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid.BlockStreaming/StreamBlocks',
            streaming__pb2.Timestamp.SerializeToString,
            streaming__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
