// Order book streaming service for grpc.
//
// Provides L2 (aggregated price levels) and L4 (individual orders) order book
// data via gRPC server-streaming RPCs. The order book state is maintained
// in-memory by the OrderBookProcessor, which consumes BookDiffs and
// OrderStatuses from the existing grpc multiplexer pipeline.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: orderbook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderBookStreaming_StreamL2Book_FullMethodName        = "/hyperliquid.OrderBookStreaming/StreamL2Book"
	OrderBookStreaming_StreamL4Book_FullMethodName        = "/hyperliquid.OrderBookStreaming/StreamL4Book"
	OrderBookStreaming_StreamBboBook_FullMethodName       = "/hyperliquid.OrderBookStreaming/StreamBboBook"
	OrderBookStreaming_StreamL2BookDiff_FullMethodName    = "/hyperliquid.OrderBookStreaming/StreamL2BookDiff"
	OrderBookStreaming_StreamL4BookUpdates_FullMethodName = "/hyperliquid.OrderBookStreaming/StreamL4BookUpdates"
	OrderBookStreaming_StreamTpslUpdates_FullMethodName   = "/hyperliquid.OrderBookStreaming/StreamTpslUpdates"
	OrderBookStreaming_StreamL2BookPacked_FullMethodName  = "/hyperliquid.OrderBookStreaming/StreamL2BookPacked"
	OrderBookStreaming_StreamBboBookPacked_FullMethodName = "/hyperliquid.OrderBookStreaming/StreamBboBookPacked"
	OrderBookStreaming_StreamL4BookBytes_FullMethodName   = "/hyperliquid.OrderBookStreaming/StreamL4BookBytes"
)

// OrderBookStreamingClient is the client API for OrderBookStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming real-time order book data.
// L2 provides aggregated price levels (px, total_sz, order_count).
// L4 provides individual order details (user, trigger info, timestamps).
type OrderBookStreamingClient interface {
	// Subscribe to L2 aggregated book updates for a coin.
	// Sends a full L2 snapshot after each block is processed.
	StreamL2Book(ctx context.Context, in *L2BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookUpdate], error)
	// Subscribe to L4 full order book for a coin.
	// Sends an initial L4 snapshot, then incremental diffs per block.
	StreamL4Book(ctx context.Context, in *L4BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookUpdate], error)
	// Subscribe to top-of-book changes. Empty coins means all coins.
	// Emits only when the best bid or ask changes for a coin.
	StreamBboBook(ctx context.Context, in *BboBookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BboBookUpdate], error)
	// Subscribe to incremental L2 price-level changes. Empty coins means all coins.
	StreamL2BookDiff(ctx context.Context, in *L2BookDiffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookDiffUpdate], error)
	// Subscribe to typed L4 order book updates. Empty coins means all coins.
	StreamL4BookUpdates(ctx context.Context, in *L4BookUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookUpdatesUpdate], error)
	// Subscribe to trigger/TP-SL order updates. Empty coins means all perp coins.
	StreamTpslUpdates(ctx context.Context, in *TpslUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TpslUpdatesUpdate], error)
	// Fast-path L2 stream. Prices/sizes are fixed-point integers scaled by 1e8.
	StreamL2BookPacked(ctx context.Context, in *L2BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookPackedUpdate], error)
	// Fast-path BBO stream. Prices/sizes are fixed-point integers scaled by 1e8.
	StreamBboBookPacked(ctx context.Context, in *BboBookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BboBookPackedUpdate], error)
	// Fast-path L4 stream. Diff payload is JSON bytes instead of a protobuf string.
	StreamL4BookBytes(ctx context.Context, in *L4BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookBytesUpdate], error)
}

type orderBookStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookStreamingClient(cc grpc.ClientConnInterface) OrderBookStreamingClient {
	return &orderBookStreamingClient{cc}
}

func (c *orderBookStreamingClient) StreamL2Book(ctx context.Context, in *L2BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[0], OrderBookStreaming_StreamL2Book_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L2BookRequest, L2BookUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookClient = grpc.ServerStreamingClient[L2BookUpdate]

func (c *orderBookStreamingClient) StreamL4Book(ctx context.Context, in *L4BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[1], OrderBookStreaming_StreamL4Book_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L4BookRequest, L4BookUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookClient = grpc.ServerStreamingClient[L4BookUpdate]

func (c *orderBookStreamingClient) StreamBboBook(ctx context.Context, in *BboBookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BboBookUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[2], OrderBookStreaming_StreamBboBook_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BboBookRequest, BboBookUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamBboBookClient = grpc.ServerStreamingClient[BboBookUpdate]

func (c *orderBookStreamingClient) StreamL2BookDiff(ctx context.Context, in *L2BookDiffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookDiffUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[3], OrderBookStreaming_StreamL2BookDiff_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L2BookDiffRequest, L2BookDiffUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookDiffClient = grpc.ServerStreamingClient[L2BookDiffUpdate]

func (c *orderBookStreamingClient) StreamL4BookUpdates(ctx context.Context, in *L4BookUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookUpdatesUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[4], OrderBookStreaming_StreamL4BookUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L4BookUpdatesRequest, L4BookUpdatesUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookUpdatesClient = grpc.ServerStreamingClient[L4BookUpdatesUpdate]

func (c *orderBookStreamingClient) StreamTpslUpdates(ctx context.Context, in *TpslUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TpslUpdatesUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[5], OrderBookStreaming_StreamTpslUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TpslUpdatesRequest, TpslUpdatesUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamTpslUpdatesClient = grpc.ServerStreamingClient[TpslUpdatesUpdate]

func (c *orderBookStreamingClient) StreamL2BookPacked(ctx context.Context, in *L2BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookPackedUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[6], OrderBookStreaming_StreamL2BookPacked_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L2BookRequest, L2BookPackedUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookPackedClient = grpc.ServerStreamingClient[L2BookPackedUpdate]

func (c *orderBookStreamingClient) StreamBboBookPacked(ctx context.Context, in *BboBookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BboBookPackedUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[7], OrderBookStreaming_StreamBboBookPacked_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BboBookRequest, BboBookPackedUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamBboBookPackedClient = grpc.ServerStreamingClient[BboBookPackedUpdate]

func (c *orderBookStreamingClient) StreamL4BookBytes(ctx context.Context, in *L4BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookBytesUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[8], OrderBookStreaming_StreamL4BookBytes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L4BookRequest, L4BookBytesUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookBytesClient = grpc.ServerStreamingClient[L4BookBytesUpdate]

// OrderBookStreamingServer is the server API for OrderBookStreaming service.
// All implementations must embed UnimplementedOrderBookStreamingServer
// for forward compatibility.
//
// Service for streaming real-time order book data.
// L2 provides aggregated price levels (px, total_sz, order_count).
// L4 provides individual order details (user, trigger info, timestamps).
type OrderBookStreamingServer interface {
	// Subscribe to L2 aggregated book updates for a coin.
	// Sends a full L2 snapshot after each block is processed.
	StreamL2Book(*L2BookRequest, grpc.ServerStreamingServer[L2BookUpdate]) error
	// Subscribe to L4 full order book for a coin.
	// Sends an initial L4 snapshot, then incremental diffs per block.
	StreamL4Book(*L4BookRequest, grpc.ServerStreamingServer[L4BookUpdate]) error
	// Subscribe to top-of-book changes. Empty coins means all coins.
	// Emits only when the best bid or ask changes for a coin.
	StreamBboBook(*BboBookRequest, grpc.ServerStreamingServer[BboBookUpdate]) error
	// Subscribe to incremental L2 price-level changes. Empty coins means all coins.
	StreamL2BookDiff(*L2BookDiffRequest, grpc.ServerStreamingServer[L2BookDiffUpdate]) error
	// Subscribe to typed L4 order book updates. Empty coins means all coins.
	StreamL4BookUpdates(*L4BookUpdatesRequest, grpc.ServerStreamingServer[L4BookUpdatesUpdate]) error
	// Subscribe to trigger/TP-SL order updates. Empty coins means all perp coins.
	StreamTpslUpdates(*TpslUpdatesRequest, grpc.ServerStreamingServer[TpslUpdatesUpdate]) error
	// Fast-path L2 stream. Prices/sizes are fixed-point integers scaled by 1e8.
	StreamL2BookPacked(*L2BookRequest, grpc.ServerStreamingServer[L2BookPackedUpdate]) error
	// Fast-path BBO stream. Prices/sizes are fixed-point integers scaled by 1e8.
	StreamBboBookPacked(*BboBookRequest, grpc.ServerStreamingServer[BboBookPackedUpdate]) error
	// Fast-path L4 stream. Diff payload is JSON bytes instead of a protobuf string.
	StreamL4BookBytes(*L4BookRequest, grpc.ServerStreamingServer[L4BookBytesUpdate]) error
	mustEmbedUnimplementedOrderBookStreamingServer()
}

// UnimplementedOrderBookStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderBookStreamingServer struct{}

func (UnimplementedOrderBookStreamingServer) StreamL2Book(*L2BookRequest, grpc.ServerStreamingServer[L2BookUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL2Book not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamL4Book(*L4BookRequest, grpc.ServerStreamingServer[L4BookUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL4Book not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamBboBook(*BboBookRequest, grpc.ServerStreamingServer[BboBookUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBboBook not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamL2BookDiff(*L2BookDiffRequest, grpc.ServerStreamingServer[L2BookDiffUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL2BookDiff not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamL4BookUpdates(*L4BookUpdatesRequest, grpc.ServerStreamingServer[L4BookUpdatesUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL4BookUpdates not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamTpslUpdates(*TpslUpdatesRequest, grpc.ServerStreamingServer[TpslUpdatesUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTpslUpdates not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamL2BookPacked(*L2BookRequest, grpc.ServerStreamingServer[L2BookPackedUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL2BookPacked not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamBboBookPacked(*BboBookRequest, grpc.ServerStreamingServer[BboBookPackedUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBboBookPacked not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamL4BookBytes(*L4BookRequest, grpc.ServerStreamingServer[L4BookBytesUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL4BookBytes not implemented")
}
func (UnimplementedOrderBookStreamingServer) mustEmbedUnimplementedOrderBookStreamingServer() {}
func (UnimplementedOrderBookStreamingServer) testEmbeddedByValue()                            {}

// UnsafeOrderBookStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderBookStreamingServer will
// result in compilation errors.
type UnsafeOrderBookStreamingServer interface {
	mustEmbedUnimplementedOrderBookStreamingServer()
}

func RegisterOrderBookStreamingServer(s grpc.ServiceRegistrar, srv OrderBookStreamingServer) {
	// If the following call pancis, it indicates UnimplementedOrderBookStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderBookStreaming_ServiceDesc, srv)
}

func _OrderBookStreaming_StreamL2Book_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L2BookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL2Book(m, &grpc.GenericServerStream[L2BookRequest, L2BookUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookServer = grpc.ServerStreamingServer[L2BookUpdate]

func _OrderBookStreaming_StreamL4Book_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L4BookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL4Book(m, &grpc.GenericServerStream[L4BookRequest, L4BookUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookServer = grpc.ServerStreamingServer[L4BookUpdate]

func _OrderBookStreaming_StreamBboBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BboBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamBboBook(m, &grpc.GenericServerStream[BboBookRequest, BboBookUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamBboBookServer = grpc.ServerStreamingServer[BboBookUpdate]

func _OrderBookStreaming_StreamL2BookDiff_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L2BookDiffRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL2BookDiff(m, &grpc.GenericServerStream[L2BookDiffRequest, L2BookDiffUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookDiffServer = grpc.ServerStreamingServer[L2BookDiffUpdate]

func _OrderBookStreaming_StreamL4BookUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L4BookUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL4BookUpdates(m, &grpc.GenericServerStream[L4BookUpdatesRequest, L4BookUpdatesUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookUpdatesServer = grpc.ServerStreamingServer[L4BookUpdatesUpdate]

func _OrderBookStreaming_StreamTpslUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TpslUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamTpslUpdates(m, &grpc.GenericServerStream[TpslUpdatesRequest, TpslUpdatesUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamTpslUpdatesServer = grpc.ServerStreamingServer[TpslUpdatesUpdate]

func _OrderBookStreaming_StreamL2BookPacked_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L2BookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL2BookPacked(m, &grpc.GenericServerStream[L2BookRequest, L2BookPackedUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookPackedServer = grpc.ServerStreamingServer[L2BookPackedUpdate]

func _OrderBookStreaming_StreamBboBookPacked_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BboBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamBboBookPacked(m, &grpc.GenericServerStream[BboBookRequest, BboBookPackedUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamBboBookPackedServer = grpc.ServerStreamingServer[BboBookPackedUpdate]

func _OrderBookStreaming_StreamL4BookBytes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L4BookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL4BookBytes(m, &grpc.GenericServerStream[L4BookRequest, L4BookBytesUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookBytesServer = grpc.ServerStreamingServer[L4BookBytesUpdate]

// OrderBookStreaming_ServiceDesc is the grpc.ServiceDesc for OrderBookStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderBookStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperliquid.OrderBookStreaming",
	HandlerType: (*OrderBookStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamL2Book",
			Handler:       _OrderBookStreaming_StreamL2Book_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamL4Book",
			Handler:       _OrderBookStreaming_StreamL4Book_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBboBook",
			Handler:       _OrderBookStreaming_StreamBboBook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamL2BookDiff",
			Handler:       _OrderBookStreaming_StreamL2BookDiff_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamL4BookUpdates",
			Handler:       _OrderBookStreaming_StreamL4BookUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTpslUpdates",
			Handler:       _OrderBookStreaming_StreamTpslUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamL2BookPacked",
			Handler:       _OrderBookStreaming_StreamL2BookPacked_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBboBookPacked",
			Handler:       _OrderBookStreaming_StreamBboBookPacked_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamL4BookBytes",
			Handler:       _OrderBookStreaming_StreamL4BookBytes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orderbook.proto",
}
