// Order book streaming service for grpc.
//
// Provides L2 (aggregated price levels) and L4 (individual orders) order book
// data via gRPC server-streaming RPCs. The order book state is maintained
// in-memory by the OrderBookProcessor, which consumes BookDiffs and
// OrderStatuses from the existing grpc multiplexer pipeline.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: orderbook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderBookStreaming_StreamL2Book_FullMethodName = "/hyperliquid.OrderBookStreaming/StreamL2Book"
	OrderBookStreaming_StreamL4Book_FullMethodName = "/hyperliquid.OrderBookStreaming/StreamL4Book"
)

// OrderBookStreamingClient is the client API for OrderBookStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming real-time order book data.
// L2 provides aggregated price levels (px, total_sz, order_count).
// L4 provides individual order details (user, trigger info, timestamps).
type OrderBookStreamingClient interface {
	// Subscribe to L2 aggregated book updates for a coin.
	// Sends a full L2 snapshot after each block is processed.
	StreamL2Book(ctx context.Context, in *L2BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookUpdate], error)
	// Subscribe to L4 full order book for a coin.
	// Sends an initial L4 snapshot, then incremental diffs per block.
	StreamL4Book(ctx context.Context, in *L4BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookUpdate], error)
}

type orderBookStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookStreamingClient(cc grpc.ClientConnInterface) OrderBookStreamingClient {
	return &orderBookStreamingClient{cc}
}

func (c *orderBookStreamingClient) StreamL2Book(ctx context.Context, in *L2BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L2BookUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[0], OrderBookStreaming_StreamL2Book_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L2BookRequest, L2BookUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookClient = grpc.ServerStreamingClient[L2BookUpdate]

func (c *orderBookStreamingClient) StreamL4Book(ctx context.Context, in *L4BookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[L4BookUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookStreaming_ServiceDesc.Streams[1], OrderBookStreaming_StreamL4Book_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[L4BookRequest, L4BookUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookClient = grpc.ServerStreamingClient[L4BookUpdate]

// OrderBookStreamingServer is the server API for OrderBookStreaming service.
// All implementations must embed UnimplementedOrderBookStreamingServer
// for forward compatibility.
//
// Service for streaming real-time order book data.
// L2 provides aggregated price levels (px, total_sz, order_count).
// L4 provides individual order details (user, trigger info, timestamps).
type OrderBookStreamingServer interface {
	// Subscribe to L2 aggregated book updates for a coin.
	// Sends a full L2 snapshot after each block is processed.
	StreamL2Book(*L2BookRequest, grpc.ServerStreamingServer[L2BookUpdate]) error
	// Subscribe to L4 full order book for a coin.
	// Sends an initial L4 snapshot, then incremental diffs per block.
	StreamL4Book(*L4BookRequest, grpc.ServerStreamingServer[L4BookUpdate]) error
	mustEmbedUnimplementedOrderBookStreamingServer()
}

// UnimplementedOrderBookStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderBookStreamingServer struct{}

func (UnimplementedOrderBookStreamingServer) StreamL2Book(*L2BookRequest, grpc.ServerStreamingServer[L2BookUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL2Book not implemented")
}
func (UnimplementedOrderBookStreamingServer) StreamL4Book(*L4BookRequest, grpc.ServerStreamingServer[L4BookUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamL4Book not implemented")
}
func (UnimplementedOrderBookStreamingServer) mustEmbedUnimplementedOrderBookStreamingServer() {}
func (UnimplementedOrderBookStreamingServer) testEmbeddedByValue()                            {}

// UnsafeOrderBookStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderBookStreamingServer will
// result in compilation errors.
type UnsafeOrderBookStreamingServer interface {
	mustEmbedUnimplementedOrderBookStreamingServer()
}

func RegisterOrderBookStreamingServer(s grpc.ServiceRegistrar, srv OrderBookStreamingServer) {
	// If the following call pancis, it indicates UnimplementedOrderBookStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderBookStreaming_ServiceDesc, srv)
}

func _OrderBookStreaming_StreamL2Book_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L2BookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL2Book(m, &grpc.GenericServerStream[L2BookRequest, L2BookUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL2BookServer = grpc.ServerStreamingServer[L2BookUpdate]

func _OrderBookStreaming_StreamL4Book_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L4BookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamingServer).StreamL4Book(m, &grpc.GenericServerStream[L4BookRequest, L4BookUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookStreaming_StreamL4BookServer = grpc.ServerStreamingServer[L4BookUpdate]

// OrderBookStreaming_ServiceDesc is the grpc.ServiceDesc for OrderBookStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderBookStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperliquid.OrderBookStreaming",
	HandlerType: (*OrderBookStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamL2Book",
			Handler:       _OrderBookStreaming_StreamL2Book_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamL4Book",
			Handler:       _OrderBookStreaming_StreamL4Book_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orderbook.proto",
}
