// Order book streaming service for grpc.
//
// Provides L2 (aggregated price levels) and L4 (individual orders) order book
// data via gRPC server-streaming RPCs. The order book state is maintained
// in-memory by the OrderBookProcessor, which consumes BookDiffs and
// OrderStatuses from the existing grpc multiplexer pipeline.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: hyperliquid/proto/orderbook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request parameters for L2 book streaming.
type L2BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	NLevels       uint32                 `protobuf:"varint,2,opt,name=n_levels,json=nLevels,proto3" json:"n_levels,omitempty"`
	NSigFigs      *uint32                `protobuf:"varint,3,opt,name=n_sig_figs,json=nSigFigs,proto3,oneof" json:"n_sig_figs,omitempty"`
	Mantissa      *uint64                `protobuf:"varint,4,opt,name=mantissa,proto3,oneof" json:"mantissa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BookRequest) Reset() {
	*x = L2BookRequest{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookRequest) ProtoMessage() {}

func (x *L2BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookRequest.ProtoReflect.Descriptor instead.
func (*L2BookRequest) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *L2BookRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L2BookRequest) GetNLevels() uint32 {
	if x != nil {
		return x.NLevels
	}
	return 0
}

func (x *L2BookRequest) GetNSigFigs() uint32 {
	if x != nil && x.NSigFigs != nil {
		return *x.NSigFigs
	}
	return 0
}

func (x *L2BookRequest) GetMantissa() uint64 {
	if x != nil && x.Mantissa != nil {
		return *x.Mantissa
	}
	return 0
}

// An L2 book update: full snapshot of aggregated price levels at a point in time.
type L2BookUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Bids          []*L2Level             `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*L2Level             `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BookUpdate) Reset() {
	*x = L2BookUpdate{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookUpdate) ProtoMessage() {}

func (x *L2BookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookUpdate.ProtoReflect.Descriptor instead.
func (*L2BookUpdate) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *L2BookUpdate) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L2BookUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L2BookUpdate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *L2BookUpdate) GetBids() []*L2Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *L2BookUpdate) GetAsks() []*L2Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

// A single aggregated price level.
type L2Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Px            string                 `protobuf:"bytes,1,opt,name=px,proto3" json:"px,omitempty"`
	Sz            string                 `protobuf:"bytes,2,opt,name=sz,proto3" json:"sz,omitempty"`
	N             uint32                 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2Level) Reset() {
	*x = L2Level{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Level) ProtoMessage() {}

func (x *L2Level) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Level.ProtoReflect.Descriptor instead.
func (*L2Level) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *L2Level) GetPx() string {
	if x != nil {
		return x.Px
	}
	return ""
}

func (x *L2Level) GetSz() string {
	if x != nil {
		return x.Sz
	}
	return ""
}

func (x *L2Level) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

// Request parameters for L4 book streaming.
type L4BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookRequest) Reset() {
	*x = L4BookRequest{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookRequest) ProtoMessage() {}

func (x *L4BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookRequest.ProtoReflect.Descriptor instead.
func (*L4BookRequest) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *L4BookRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

// An L4 book update: either a full snapshot or an incremental diff.
type L4BookUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*L4BookUpdate_Snapshot
	//	*L4BookUpdate_Diff
	Update        isL4BookUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookUpdate) Reset() {
	*x = L4BookUpdate{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookUpdate) ProtoMessage() {}

func (x *L4BookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookUpdate.ProtoReflect.Descriptor instead.
func (*L4BookUpdate) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *L4BookUpdate) GetUpdate() isL4BookUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *L4BookUpdate) GetSnapshot() *L4BookSnapshot {
	if x != nil {
		if x, ok := x.Update.(*L4BookUpdate_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *L4BookUpdate) GetDiff() *L4BookDiff {
	if x != nil {
		if x, ok := x.Update.(*L4BookUpdate_Diff); ok {
			return x.Diff
		}
	}
	return nil
}

type isL4BookUpdate_Update interface {
	isL4BookUpdate_Update()
}

type L4BookUpdate_Snapshot struct {
	Snapshot *L4BookSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type L4BookUpdate_Diff struct {
	Diff *L4BookDiff `protobuf:"bytes,2,opt,name=diff,proto3,oneof"`
}

func (*L4BookUpdate_Snapshot) isL4BookUpdate_Update() {}

func (*L4BookUpdate_Diff) isL4BookUpdate_Update() {}

// Full L4 order book snapshot for a single coin.
type L4BookSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Bids          []*L4Order             `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*L4Order             `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookSnapshot) Reset() {
	*x = L4BookSnapshot{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookSnapshot) ProtoMessage() {}

func (x *L4BookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookSnapshot.ProtoReflect.Descriptor instead.
func (*L4BookSnapshot) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *L4BookSnapshot) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L4BookSnapshot) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L4BookSnapshot) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L4BookSnapshot) GetBids() []*L4Order {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *L4BookSnapshot) GetAsks() []*L4Order {
	if x != nil {
		return x.Asks
	}
	return nil
}

// Incremental L4 book diff: raw order statuses and book diffs for one block.
type L4BookDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookDiff) Reset() {
	*x = L4BookDiff{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookDiff) ProtoMessage() {}

func (x *L4BookDiff) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookDiff.ProtoReflect.Descriptor instead.
func (*L4BookDiff) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *L4BookDiff) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L4BookDiff) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L4BookDiff) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// A single L4 order with full details.
type L4Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	User             string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Coin             string                 `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Side             string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	LimitPx          string                 `protobuf:"bytes,4,opt,name=limit_px,json=limitPx,proto3" json:"limit_px,omitempty"`
	Sz               string                 `protobuf:"bytes,5,opt,name=sz,proto3" json:"sz,omitempty"`
	Oid              uint64                 `protobuf:"varint,6,opt,name=oid,proto3" json:"oid,omitempty"`
	Timestamp        uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TriggerCondition string                 `protobuf:"bytes,8,opt,name=trigger_condition,json=triggerCondition,proto3" json:"trigger_condition,omitempty"`
	IsTrigger        bool                   `protobuf:"varint,9,opt,name=is_trigger,json=isTrigger,proto3" json:"is_trigger,omitempty"`
	TriggerPx        string                 `protobuf:"bytes,10,opt,name=trigger_px,json=triggerPx,proto3" json:"trigger_px,omitempty"`
	IsPositionTpsl   bool                   `protobuf:"varint,11,opt,name=is_position_tpsl,json=isPositionTpsl,proto3" json:"is_position_tpsl,omitempty"`
	ReduceOnly       bool                   `protobuf:"varint,12,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	OrderType        string                 `protobuf:"bytes,13,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Tif              *string                `protobuf:"bytes,14,opt,name=tif,proto3,oneof" json:"tif,omitempty"`
	Cloid            *string                `protobuf:"bytes,15,opt,name=cloid,proto3,oneof" json:"cloid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *L4Order) Reset() {
	*x = L4Order{}
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4Order) ProtoMessage() {}

func (x *L4Order) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_orderbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4Order.ProtoReflect.Descriptor instead.
func (*L4Order) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *L4Order) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *L4Order) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L4Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *L4Order) GetLimitPx() string {
	if x != nil {
		return x.LimitPx
	}
	return ""
}

func (x *L4Order) GetSz() string {
	if x != nil {
		return x.Sz
	}
	return ""
}

func (x *L4Order) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *L4Order) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *L4Order) GetTriggerCondition() string {
	if x != nil {
		return x.TriggerCondition
	}
	return ""
}

func (x *L4Order) GetIsTrigger() bool {
	if x != nil {
		return x.IsTrigger
	}
	return false
}

func (x *L4Order) GetTriggerPx() string {
	if x != nil {
		return x.TriggerPx
	}
	return ""
}

func (x *L4Order) GetIsPositionTpsl() bool {
	if x != nil {
		return x.IsPositionTpsl
	}
	return false
}

func (x *L4Order) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *L4Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *L4Order) GetTif() string {
	if x != nil && x.Tif != nil {
		return *x.Tif
	}
	return ""
}

func (x *L4Order) GetCloid() string {
	if x != nil && x.Cloid != nil {
		return *x.Cloid
	}
	return ""
}

var File_hyperliquid_proto_orderbook_proto protoreflect.FileDescriptor

const file_hyperliquid_proto_orderbook_proto_rawDesc = "" +
	"\n" +
	"!hyperliquid/proto/orderbook.proto\x12\vhyperliquid\"\x9e\x01\n" +
	"\rL2BookRequest\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x19\n" +
	"\bn_levels\x18\x02 \x01(\rR\anLevels\x12!\n" +
	"\n" +
	"n_sig_figs\x18\x03 \x01(\rH\x00R\bnSigFigs\x88\x01\x01\x12\x1f\n" +
	"\bmantissa\x18\x04 \x01(\x04H\x01R\bmantissa\x88\x01\x01B\r\n" +
	"\v_n_sig_figsB\v\n" +
	"\t_mantissa\"\xad\x01\n" +
	"\fL2BookUpdate\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12(\n" +
	"\x04bids\x18\x04 \x03(\v2\x14.hyperliquid.L2LevelR\x04bids\x12(\n" +
	"\x04asks\x18\x05 \x03(\v2\x14.hyperliquid.L2LevelR\x04asks\"7\n" +
	"\aL2Level\x12\x0e\n" +
	"\x02px\x18\x01 \x01(\tR\x02px\x12\x0e\n" +
	"\x02sz\x18\x02 \x01(\tR\x02sz\x12\f\n" +
	"\x01n\x18\x03 \x01(\rR\x01n\"#\n" +
	"\rL4BookRequest\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\"\x82\x01\n" +
	"\fL4BookUpdate\x129\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.hyperliquid.L4BookSnapshotH\x00R\bsnapshot\x12-\n" +
	"\x04diff\x18\x02 \x01(\v2\x17.hyperliquid.L4BookDiffH\x00R\x04diffB\b\n" +
	"\x06update\"\xa4\x01\n" +
	"\x0eL4BookSnapshot\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12(\n" +
	"\x04bids\x18\x04 \x03(\v2\x14.hyperliquid.L4OrderR\x04bids\x12(\n" +
	"\x04asks\x18\x05 \x03(\v2\x14.hyperliquid.L4OrderR\x04asks\"L\n" +
	"\n" +
	"L4BookDiff\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\xb9\x03\n" +
	"\aL4Order\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\tR\x04coin\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x19\n" +
	"\blimit_px\x18\x04 \x01(\tR\alimitPx\x12\x0e\n" +
	"\x02sz\x18\x05 \x01(\tR\x02sz\x12\x10\n" +
	"\x03oid\x18\x06 \x01(\x04R\x03oid\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x12+\n" +
	"\x11trigger_condition\x18\b \x01(\tR\x10triggerCondition\x12\x1d\n" +
	"\n" +
	"is_trigger\x18\t \x01(\bR\tisTrigger\x12\x1d\n" +
	"\n" +
	"trigger_px\x18\n" +
	" \x01(\tR\ttriggerPx\x12(\n" +
	"\x10is_position_tpsl\x18\v \x01(\bR\x0eisPositionTpsl\x12\x1f\n" +
	"\vreduce_only\x18\f \x01(\bR\n" +
	"reduceOnly\x12\x1d\n" +
	"\n" +
	"order_type\x18\r \x01(\tR\torderType\x12\x15\n" +
	"\x03tif\x18\x0e \x01(\tH\x00R\x03tif\x88\x01\x01\x12\x19\n" +
	"\x05cloid\x18\x0f \x01(\tH\x01R\x05cloid\x88\x01\x01B\x06\n" +
	"\x04_tifB\b\n" +
	"\x06_cloid2\xa6\x01\n" +
	"\x12OrderBookStreaming\x12G\n" +
	"\fStreamL2Book\x12\x1a.hyperliquid.L2BookRequest\x1a\x19.hyperliquid.L2BookUpdate0\x01\x12G\n" +
	"\fStreamL4Book\x12\x1a.hyperliquid.L4BookRequest\x1a\x19.hyperliquid.L4BookUpdate0\x01BFZDgithub.com/quiknode-labs/raptor/hyperliquid-sdk/go/hyperliquid/protob\x06proto3"

var (
	file_hyperliquid_proto_orderbook_proto_rawDescOnce sync.Once
	file_hyperliquid_proto_orderbook_proto_rawDescData []byte
)

func file_hyperliquid_proto_orderbook_proto_rawDescGZIP() []byte {
	file_hyperliquid_proto_orderbook_proto_rawDescOnce.Do(func() {
		file_hyperliquid_proto_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperliquid_proto_orderbook_proto_rawDesc), len(file_hyperliquid_proto_orderbook_proto_rawDesc)))
	})
	return file_hyperliquid_proto_orderbook_proto_rawDescData
}

var file_hyperliquid_proto_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hyperliquid_proto_orderbook_proto_goTypes = []any{
	(*L2BookRequest)(nil),  // 0: hyperliquid.L2BookRequest
	(*L2BookUpdate)(nil),   // 1: hyperliquid.L2BookUpdate
	(*L2Level)(nil),        // 2: hyperliquid.L2Level
	(*L4BookRequest)(nil),  // 3: hyperliquid.L4BookRequest
	(*L4BookUpdate)(nil),   // 4: hyperliquid.L4BookUpdate
	(*L4BookSnapshot)(nil), // 5: hyperliquid.L4BookSnapshot
	(*L4BookDiff)(nil),     // 6: hyperliquid.L4BookDiff
	(*L4Order)(nil),        // 7: hyperliquid.L4Order
}
var file_hyperliquid_proto_orderbook_proto_depIdxs = []int32{
	2, // 0: hyperliquid.L2BookUpdate.bids:type_name -> hyperliquid.L2Level
	2, // 1: hyperliquid.L2BookUpdate.asks:type_name -> hyperliquid.L2Level
	5, // 2: hyperliquid.L4BookUpdate.snapshot:type_name -> hyperliquid.L4BookSnapshot
	6, // 3: hyperliquid.L4BookUpdate.diff:type_name -> hyperliquid.L4BookDiff
	7, // 4: hyperliquid.L4BookSnapshot.bids:type_name -> hyperliquid.L4Order
	7, // 5: hyperliquid.L4BookSnapshot.asks:type_name -> hyperliquid.L4Order
	0, // 6: hyperliquid.OrderBookStreaming.StreamL2Book:input_type -> hyperliquid.L2BookRequest
	3, // 7: hyperliquid.OrderBookStreaming.StreamL4Book:input_type -> hyperliquid.L4BookRequest
	1, // 8: hyperliquid.OrderBookStreaming.StreamL2Book:output_type -> hyperliquid.L2BookUpdate
	4, // 9: hyperliquid.OrderBookStreaming.StreamL4Book:output_type -> hyperliquid.L4BookUpdate
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hyperliquid_proto_orderbook_proto_init() }
func file_hyperliquid_proto_orderbook_proto_init() {
	if File_hyperliquid_proto_orderbook_proto != nil {
		return
	}
	file_hyperliquid_proto_orderbook_proto_msgTypes[0].OneofWrappers = []any{}
	file_hyperliquid_proto_orderbook_proto_msgTypes[4].OneofWrappers = []any{
		(*L4BookUpdate_Snapshot)(nil),
		(*L4BookUpdate_Diff)(nil),
	}
	file_hyperliquid_proto_orderbook_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperliquid_proto_orderbook_proto_rawDesc), len(file_hyperliquid_proto_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyperliquid_proto_orderbook_proto_goTypes,
		DependencyIndexes: file_hyperliquid_proto_orderbook_proto_depIdxs,
		MessageInfos:      file_hyperliquid_proto_orderbook_proto_msgTypes,
	}.Build()
	File_hyperliquid_proto_orderbook_proto = out.File
	file_hyperliquid_proto_orderbook_proto_goTypes = nil
	file_hyperliquid_proto_orderbook_proto_depIdxs = nil
}
