// Order book streaming service for grpc.
//
// Provides L2 (aggregated price levels) and L4 (individual orders) order book
// data via gRPC server-streaming RPCs. The order book state is maintained
// in-memory by the OrderBookProcessor, which consumes BookDiffs and
// OrderStatuses from the existing grpc multiplexer pipeline.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: orderbook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L4OrderDiffType int32

const (
	L4OrderDiffType_L4_ORDER_DIFF_TYPE_UNSPECIFIED L4OrderDiffType = 0
	L4OrderDiffType_L4_ORDER_DIFF_TYPE_NEW         L4OrderDiffType = 1
	L4OrderDiffType_L4_ORDER_DIFF_TYPE_UPDATE      L4OrderDiffType = 2
	L4OrderDiffType_L4_ORDER_DIFF_TYPE_REMOVE      L4OrderDiffType = 3
)

// Enum value maps for L4OrderDiffType.
var (
	L4OrderDiffType_name = map[int32]string{
		0: "L4_ORDER_DIFF_TYPE_UNSPECIFIED",
		1: "L4_ORDER_DIFF_TYPE_NEW",
		2: "L4_ORDER_DIFF_TYPE_UPDATE",
		3: "L4_ORDER_DIFF_TYPE_REMOVE",
	}
	L4OrderDiffType_value = map[string]int32{
		"L4_ORDER_DIFF_TYPE_UNSPECIFIED": 0,
		"L4_ORDER_DIFF_TYPE_NEW":         1,
		"L4_ORDER_DIFF_TYPE_UPDATE":      2,
		"L4_ORDER_DIFF_TYPE_REMOVE":      3,
	}
)

func (x L4OrderDiffType) Enum() *L4OrderDiffType {
	p := new(L4OrderDiffType)
	*p = x
	return p
}

func (x L4OrderDiffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L4OrderDiffType) Descriptor() protoreflect.EnumDescriptor {
	return file_orderbook_proto_enumTypes[0].Descriptor()
}

func (L4OrderDiffType) Type() protoreflect.EnumType {
	return &file_orderbook_proto_enumTypes[0]
}

func (x L4OrderDiffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L4OrderDiffType.Descriptor instead.
func (L4OrderDiffType) EnumDescriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{0}
}

type TpslDiffType int32

const (
	TpslDiffType_TPSL_DIFF_TYPE_UNSPECIFIED TpslDiffType = 0
	TpslDiffType_TPSL_DIFF_TYPE_ADD         TpslDiffType = 1
	TpslDiffType_TPSL_DIFF_TYPE_REMOVE      TpslDiffType = 2
)

// Enum value maps for TpslDiffType.
var (
	TpslDiffType_name = map[int32]string{
		0: "TPSL_DIFF_TYPE_UNSPECIFIED",
		1: "TPSL_DIFF_TYPE_ADD",
		2: "TPSL_DIFF_TYPE_REMOVE",
	}
	TpslDiffType_value = map[string]int32{
		"TPSL_DIFF_TYPE_UNSPECIFIED": 0,
		"TPSL_DIFF_TYPE_ADD":         1,
		"TPSL_DIFF_TYPE_REMOVE":      2,
	}
)

func (x TpslDiffType) Enum() *TpslDiffType {
	p := new(TpslDiffType)
	*p = x
	return p
}

func (x TpslDiffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TpslDiffType) Descriptor() protoreflect.EnumDescriptor {
	return file_orderbook_proto_enumTypes[1].Descriptor()
}

func (TpslDiffType) Type() protoreflect.EnumType {
	return &file_orderbook_proto_enumTypes[1]
}

func (x TpslDiffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TpslDiffType.Descriptor instead.
func (TpslDiffType) EnumDescriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{1}
}

// Request parameters for L2 book streaming.
type L2BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`                                  // Symbol (e.g. "BTC", "ETH")
	NLevels       uint32                 `protobuf:"varint,2,opt,name=n_levels,json=nLevels,proto3" json:"n_levels,omitempty"`            // Max number of price levels (default 20, max 100)
	NSigFigs      *uint32                `protobuf:"varint,3,opt,name=n_sig_figs,json=nSigFigs,proto3,oneof" json:"n_sig_figs,omitempty"` // Significance figures for price bucketing (2-5)
	Mantissa      *uint64                `protobuf:"varint,4,opt,name=mantissa,proto3,oneof" json:"mantissa,omitempty"`                   // Mantissa for bucketing (1, 2, or 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BookRequest) Reset() {
	*x = L2BookRequest{}
	mi := &file_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookRequest) ProtoMessage() {}

func (x *L2BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookRequest.ProtoReflect.Descriptor instead.
func (*L2BookRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *L2BookRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L2BookRequest) GetNLevels() uint32 {
	if x != nil {
		return x.NLevels
	}
	return 0
}

func (x *L2BookRequest) GetNSigFigs() uint32 {
	if x != nil && x.NSigFigs != nil {
		return *x.NSigFigs
	}
	return 0
}

func (x *L2BookRequest) GetMantissa() uint64 {
	if x != nil && x.Mantissa != nil {
		return *x.Mantissa
	}
	return 0
}

// An L2 book update: full snapshot of aggregated price levels at a point in time.
type L2BookUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"` // Block timestamp (milliseconds)
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Bids          []*L2Level             `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"` // Aggregated bid levels (best first)
	Asks          []*L2Level             `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"` // Aggregated ask levels (best first)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BookUpdate) Reset() {
	*x = L2BookUpdate{}
	mi := &file_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookUpdate) ProtoMessage() {}

func (x *L2BookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookUpdate.ProtoReflect.Descriptor instead.
func (*L2BookUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *L2BookUpdate) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L2BookUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L2BookUpdate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *L2BookUpdate) GetBids() []*L2Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *L2BookUpdate) GetAsks() []*L2Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

// A single aggregated price level.
type L2Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Px            string                 `protobuf:"bytes,1,opt,name=px,proto3" json:"px,omitempty"` // Price as decimal string
	Sz            string                 `protobuf:"bytes,2,opt,name=sz,proto3" json:"sz,omitempty"` // Total size as decimal string
	N             uint32                 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`  // Number of individual orders at this level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2Level) Reset() {
	*x = L2Level{}
	mi := &file_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Level) ProtoMessage() {}

func (x *L2Level) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Level.ProtoReflect.Descriptor instead.
func (*L2Level) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *L2Level) GetPx() string {
	if x != nil {
		return x.Px
	}
	return ""
}

func (x *L2Level) GetSz() string {
	if x != nil {
		return x.Sz
	}
	return ""
}

func (x *L2Level) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type L2LevelPacked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Px            uint64                 `protobuf:"fixed64,1,opt,name=px,proto3" json:"px,omitempty"` // Price scaled by 1e8
	Sz            uint64                 `protobuf:"fixed64,2,opt,name=sz,proto3" json:"sz,omitempty"` // Size scaled by 1e8
	N             uint32                 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`    // Number of individual orders at this level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2LevelPacked) Reset() {
	*x = L2LevelPacked{}
	mi := &file_orderbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2LevelPacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2LevelPacked) ProtoMessage() {}

func (x *L2LevelPacked) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2LevelPacked.ProtoReflect.Descriptor instead.
func (*L2LevelPacked) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *L2LevelPacked) GetPx() uint64 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *L2LevelPacked) GetSz() uint64 {
	if x != nil {
		return x.Sz
	}
	return 0
}

func (x *L2LevelPacked) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type L2BookPackedUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Bids          []*L2LevelPacked       `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*L2LevelPacked       `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BookPackedUpdate) Reset() {
	*x = L2BookPackedUpdate{}
	mi := &file_orderbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookPackedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookPackedUpdate) ProtoMessage() {}

func (x *L2BookPackedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookPackedUpdate.ProtoReflect.Descriptor instead.
func (*L2BookPackedUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *L2BookPackedUpdate) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L2BookPackedUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L2BookPackedUpdate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *L2BookPackedUpdate) GetBids() []*L2LevelPacked {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *L2BookPackedUpdate) GetAsks() []*L2LevelPacked {
	if x != nil {
		return x.Asks
	}
	return nil
}

// Request parameters for best bid/offer streaming.
type BboBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coins         []string               `protobuf:"bytes,1,rep,name=coins,proto3" json:"coins,omitempty"` // Empty means all coins
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BboBookRequest) Reset() {
	*x = BboBookRequest{}
	mi := &file_orderbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BboBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BboBookRequest) ProtoMessage() {}

func (x *BboBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BboBookRequest.ProtoReflect.Descriptor instead.
func (*BboBookRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *BboBookRequest) GetCoins() []string {
	if x != nil {
		return x.Coins
	}
	return nil
}

// Best bid/offer update for a coin.
type BboBookUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"` // Block timestamp (milliseconds)
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Bid           *L2Level               `protobuf:"bytes,4,opt,name=bid,proto3" json:"bid,omitempty"` // Absent if no bid
	Ask           *L2Level               `protobuf:"bytes,5,opt,name=ask,proto3" json:"ask,omitempty"` // Absent if no ask
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BboBookUpdate) Reset() {
	*x = BboBookUpdate{}
	mi := &file_orderbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BboBookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BboBookUpdate) ProtoMessage() {}

func (x *BboBookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BboBookUpdate.ProtoReflect.Descriptor instead.
func (*BboBookUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *BboBookUpdate) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *BboBookUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BboBookUpdate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BboBookUpdate) GetBid() *L2Level {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *BboBookUpdate) GetAsk() *L2Level {
	if x != nil {
		return x.Ask
	}
	return nil
}

type BboBookPackedUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Bid           *L2LevelPacked         `protobuf:"bytes,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           *L2LevelPacked         `protobuf:"bytes,5,opt,name=ask,proto3" json:"ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BboBookPackedUpdate) Reset() {
	*x = BboBookPackedUpdate{}
	mi := &file_orderbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BboBookPackedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BboBookPackedUpdate) ProtoMessage() {}

func (x *BboBookPackedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BboBookPackedUpdate.ProtoReflect.Descriptor instead.
func (*BboBookPackedUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *BboBookPackedUpdate) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *BboBookPackedUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BboBookPackedUpdate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BboBookPackedUpdate) GetBid() *L2LevelPacked {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *BboBookPackedUpdate) GetAsk() *L2LevelPacked {
	if x != nil {
		return x.Ask
	}
	return nil
}

// Request parameters for L2 diff streaming.
type L2BookDiffRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Coins               []string               `protobuf:"bytes,1,rep,name=coins,proto3" json:"coins,omitempty"`                                                           // Empty means all coins
	NLevels             uint32                 `protobuf:"varint,2,opt,name=n_levels,json=nLevels,proto3" json:"n_levels,omitempty"`                                       // Max tracked levels per side (default 20, max 100)
	NSigFigs            *uint32                `protobuf:"varint,3,opt,name=n_sig_figs,json=nSigFigs,proto3,oneof" json:"n_sig_figs,omitempty"`                            // Significance figures for price bucketing (2-5)
	Mantissa            *uint64                `protobuf:"varint,4,opt,name=mantissa,proto3,oneof" json:"mantissa,omitempty"`                                              // Mantissa for bucketing (1, 2, or 5)
	SkipInitialSnapshot bool                   `protobuf:"varint,5,opt,name=skip_initial_snapshot,json=skipInitialSnapshot,proto3" json:"skip_initial_snapshot,omitempty"` // If false, first update per coin contains current levels
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *L2BookDiffRequest) Reset() {
	*x = L2BookDiffRequest{}
	mi := &file_orderbook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookDiffRequest) ProtoMessage() {}

func (x *L2BookDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookDiffRequest.ProtoReflect.Descriptor instead.
func (*L2BookDiffRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *L2BookDiffRequest) GetCoins() []string {
	if x != nil {
		return x.Coins
	}
	return nil
}

func (x *L2BookDiffRequest) GetNLevels() uint32 {
	if x != nil {
		return x.NLevels
	}
	return 0
}

func (x *L2BookDiffRequest) GetNSigFigs() uint32 {
	if x != nil && x.NSigFigs != nil {
		return *x.NSigFigs
	}
	return 0
}

func (x *L2BookDiffRequest) GetMantissa() uint64 {
	if x != nil && x.Mantissa != nil {
		return *x.Mantissa
	}
	return 0
}

func (x *L2BookDiffRequest) GetSkipInitialSnapshot() bool {
	if x != nil {
		return x.SkipInitialSnapshot
	}
	return false
}

// Batch of L2 price-level changes for one processed block.
type L2BookDiffUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`         // Block timestamp (milliseconds)
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`     // Block height
	Snapshot      bool                   `protobuf:"varint,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // True when carrying initial levels for any coin
	Diffs         []*L2CoinDiff          `protobuf:"bytes,4,rep,name=diffs,proto3" json:"diffs,omitempty"`        // Only coins with changed levels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BookDiffUpdate) Reset() {
	*x = L2BookDiffUpdate{}
	mi := &file_orderbook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BookDiffUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BookDiffUpdate) ProtoMessage() {}

func (x *L2BookDiffUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BookDiffUpdate.ProtoReflect.Descriptor instead.
func (*L2BookDiffUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{9}
}

func (x *L2BookDiffUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L2BookDiffUpdate) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L2BookDiffUpdate) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *L2BookDiffUpdate) GetDiffs() []*L2CoinDiff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

// Incremental L2 changes for one coin.
type L2CoinDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"` // Per-coin sequence in this stream
	PrevSeq       uint64                 `protobuf:"varint,3,opt,name=prev_seq,json=prevSeq,proto3" json:"prev_seq,omitempty"`
	Bids          []*L2Level             `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`          // Changed bid levels; sz=0 means removed
	Asks          []*L2Level             `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`          // Changed ask levels; sz=0 means removed
	Snapshot      bool                   `protobuf:"varint,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // True when bids/asks carry initial levels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2CoinDiff) Reset() {
	*x = L2CoinDiff{}
	mi := &file_orderbook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2CoinDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2CoinDiff) ProtoMessage() {}

func (x *L2CoinDiff) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2CoinDiff.ProtoReflect.Descriptor instead.
func (*L2CoinDiff) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{10}
}

func (x *L2CoinDiff) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L2CoinDiff) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *L2CoinDiff) GetPrevSeq() uint64 {
	if x != nil {
		return x.PrevSeq
	}
	return 0
}

func (x *L2CoinDiff) GetBids() []*L2Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *L2CoinDiff) GetAsks() []*L2Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *L2CoinDiff) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

// Request parameters for L4 book streaming.
type L4BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"` // Symbol (e.g. "BTC", "ETH")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookRequest) Reset() {
	*x = L4BookRequest{}
	mi := &file_orderbook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookRequest) ProtoMessage() {}

func (x *L4BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookRequest.ProtoReflect.Descriptor instead.
func (*L4BookRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{11}
}

func (x *L4BookRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

// An L4 book update: either a full snapshot or an incremental diff.
type L4BookUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*L4BookUpdate_Snapshot
	//	*L4BookUpdate_Diff
	Update        isL4BookUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookUpdate) Reset() {
	*x = L4BookUpdate{}
	mi := &file_orderbook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookUpdate) ProtoMessage() {}

func (x *L4BookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookUpdate.ProtoReflect.Descriptor instead.
func (*L4BookUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{12}
}

func (x *L4BookUpdate) GetUpdate() isL4BookUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *L4BookUpdate) GetSnapshot() *L4BookSnapshot {
	if x != nil {
		if x, ok := x.Update.(*L4BookUpdate_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *L4BookUpdate) GetDiff() *L4BookDiff {
	if x != nil {
		if x, ok := x.Update.(*L4BookUpdate_Diff); ok {
			return x.Diff
		}
	}
	return nil
}

type isL4BookUpdate_Update interface {
	isL4BookUpdate_Update()
}

type L4BookUpdate_Snapshot struct {
	Snapshot *L4BookSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // Full snapshot (sent on subscribe)
}

type L4BookUpdate_Diff struct {
	Diff *L4BookDiff `protobuf:"bytes,2,opt,name=diff,proto3,oneof"` // Incremental diff (sent per block)
}

func (*L4BookUpdate_Snapshot) isL4BookUpdate_Update() {}

func (*L4BookUpdate_Diff) isL4BookUpdate_Update() {}

// Full L4 order book snapshot for a single coin.
type L4BookSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Bids          []*L4Order             `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*L4Order             `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookSnapshot) Reset() {
	*x = L4BookSnapshot{}
	mi := &file_orderbook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookSnapshot) ProtoMessage() {}

func (x *L4BookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookSnapshot.ProtoReflect.Descriptor instead.
func (*L4BookSnapshot) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{13}
}

func (x *L4BookSnapshot) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L4BookSnapshot) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L4BookSnapshot) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L4BookSnapshot) GetBids() []*L4Order {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *L4BookSnapshot) GetAsks() []*L4Order {
	if x != nil {
		return x.Asks
	}
	return nil
}

// Incremental L4 book diff: raw order statuses and book diffs for one block.
// Sent as JSON to preserve the original node data format.
type L4BookDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded {order_statuses, book_diffs}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookDiff) Reset() {
	*x = L4BookDiff{}
	mi := &file_orderbook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookDiff) ProtoMessage() {}

func (x *L4BookDiff) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookDiff.ProtoReflect.Descriptor instead.
func (*L4BookDiff) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{14}
}

func (x *L4BookDiff) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L4BookDiff) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L4BookDiff) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type L4BookBytesUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*L4BookBytesUpdate_Snapshot
	//	*L4BookBytesUpdate_Diff
	Update        isL4BookBytesUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookBytesUpdate) Reset() {
	*x = L4BookBytesUpdate{}
	mi := &file_orderbook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookBytesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookBytesUpdate) ProtoMessage() {}

func (x *L4BookBytesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookBytesUpdate.ProtoReflect.Descriptor instead.
func (*L4BookBytesUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{15}
}

func (x *L4BookBytesUpdate) GetUpdate() isL4BookBytesUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *L4BookBytesUpdate) GetSnapshot() *L4BookSnapshot {
	if x != nil {
		if x, ok := x.Update.(*L4BookBytesUpdate_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *L4BookBytesUpdate) GetDiff() *L4BookBytesDiff {
	if x != nil {
		if x, ok := x.Update.(*L4BookBytesUpdate_Diff); ok {
			return x.Diff
		}
	}
	return nil
}

type isL4BookBytesUpdate_Update interface {
	isL4BookBytesUpdate_Update()
}

type L4BookBytesUpdate_Snapshot struct {
	Snapshot *L4BookSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // Full snapshot (sent on subscribe)
}

type L4BookBytesUpdate_Diff struct {
	Diff *L4BookBytesDiff `protobuf:"bytes,2,opt,name=diff,proto3,oneof"` // Incremental diff bytes
}

func (*L4BookBytesUpdate_Snapshot) isL4BookBytesUpdate_Update() {}

func (*L4BookBytesUpdate_Diff) isL4BookBytesUpdate_Update() {}

type L4BookBytesDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded {order_statuses, book_diffs}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookBytesDiff) Reset() {
	*x = L4BookBytesDiff{}
	mi := &file_orderbook_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookBytesDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookBytesDiff) ProtoMessage() {}

func (x *L4BookBytesDiff) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookBytesDiff.ProtoReflect.Descriptor instead.
func (*L4BookBytesDiff) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{16}
}

func (x *L4BookBytesDiff) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L4BookBytesDiff) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L4BookBytesDiff) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request parameters for typed L4 order updates.
type L4BookUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coins         []string               `protobuf:"bytes,1,rep,name=coins,proto3" json:"coins,omitempty"` // Empty means all coins
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookUpdatesRequest) Reset() {
	*x = L4BookUpdatesRequest{}
	mi := &file_orderbook_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookUpdatesRequest) ProtoMessage() {}

func (x *L4BookUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookUpdatesRequest.ProtoReflect.Descriptor instead.
func (*L4BookUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{17}
}

func (x *L4BookUpdatesRequest) GetCoins() []string {
	if x != nil {
		return x.Coins
	}
	return nil
}

// Typed L4 order book update batch for one processed block.
type L4BookUpdatesUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Diffs         []*L4OrderDiff         `protobuf:"bytes,3,rep,name=diffs,proto3" json:"diffs,omitempty"`
	Snapshot      bool                   `protobuf:"varint,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // True when diffs carry a full reset snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4BookUpdatesUpdate) Reset() {
	*x = L4BookUpdatesUpdate{}
	mi := &file_orderbook_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4BookUpdatesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4BookUpdatesUpdate) ProtoMessage() {}

func (x *L4BookUpdatesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4BookUpdatesUpdate.ProtoReflect.Descriptor instead.
func (*L4BookUpdatesUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{18}
}

func (x *L4BookUpdatesUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L4BookUpdatesUpdate) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *L4BookUpdatesUpdate) GetDiffs() []*L4OrderDiff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

func (x *L4BookUpdatesUpdate) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

// A single typed L4 order-level change.
type L4OrderDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiffType      L4OrderDiffType        `protobuf:"varint,1,opt,name=diff_type,json=diffType,proto3,enum=hyperliquid.L4OrderDiffType" json:"diff_type,omitempty"`
	Coin          string                 `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Oid           uint64                 `protobuf:"varint,3,opt,name=oid,proto3" json:"oid,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Side          string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"` // "A" (Ask) or "B" (Bid)
	Px            string                 `protobuf:"bytes,6,opt,name=px,proto3" json:"px,omitempty"`
	Sz            string                 `protobuf:"bytes,7,opt,name=sz,proto3" json:"sz,omitempty"` // New/current size for new/update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4OrderDiff) Reset() {
	*x = L4OrderDiff{}
	mi := &file_orderbook_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4OrderDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4OrderDiff) ProtoMessage() {}

func (x *L4OrderDiff) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4OrderDiff.ProtoReflect.Descriptor instead.
func (*L4OrderDiff) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{19}
}

func (x *L4OrderDiff) GetDiffType() L4OrderDiffType {
	if x != nil {
		return x.DiffType
	}
	return L4OrderDiffType_L4_ORDER_DIFF_TYPE_UNSPECIFIED
}

func (x *L4OrderDiff) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L4OrderDiff) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *L4OrderDiff) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *L4OrderDiff) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *L4OrderDiff) GetPx() string {
	if x != nil {
		return x.Px
	}
	return ""
}

func (x *L4OrderDiff) GetSz() string {
	if x != nil {
		return x.Sz
	}
	return ""
}

// A single L4 order with full details.
type L4Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	User             string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // Ethereum address
	Coin             string                 `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Side             string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`                                                 // "A" (Ask) or "B" (Bid)
	LimitPx          string                 `protobuf:"bytes,4,opt,name=limit_px,json=limitPx,proto3" json:"limit_px,omitempty"`                            // Limit price as decimal string
	Sz               string                 `protobuf:"bytes,5,opt,name=sz,proto3" json:"sz,omitempty"`                                                     // Size as decimal string
	Oid              uint64                 `protobuf:"varint,6,opt,name=oid,proto3" json:"oid,omitempty"`                                                  // Unique order ID
	Timestamp        uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // When order entered the book (ms)
	TriggerCondition string                 `protobuf:"bytes,8,opt,name=trigger_condition,json=triggerCondition,proto3" json:"trigger_condition,omitempty"` // "N/A", "Triggered", etc.
	IsTrigger        bool                   `protobuf:"varint,9,opt,name=is_trigger,json=isTrigger,proto3" json:"is_trigger,omitempty"`
	TriggerPx        string                 `protobuf:"bytes,10,opt,name=trigger_px,json=triggerPx,proto3" json:"trigger_px,omitempty"`
	IsPositionTpsl   bool                   `protobuf:"varint,11,opt,name=is_position_tpsl,json=isPositionTpsl,proto3" json:"is_position_tpsl,omitempty"`
	ReduceOnly       bool                   `protobuf:"varint,12,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	OrderType        string                 `protobuf:"bytes,13,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // "Limit", "Market", etc.
	Tif              *string                `protobuf:"bytes,14,opt,name=tif,proto3,oneof" json:"tif,omitempty"`                        // Time-in-force: "Gtc", "Ioc", "Alo"
	Cloid            *string                `protobuf:"bytes,15,opt,name=cloid,proto3,oneof" json:"cloid,omitempty"`                    // Client order ID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *L4Order) Reset() {
	*x = L4Order{}
	mi := &file_orderbook_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4Order) ProtoMessage() {}

func (x *L4Order) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4Order.ProtoReflect.Descriptor instead.
func (*L4Order) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{20}
}

func (x *L4Order) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *L4Order) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *L4Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *L4Order) GetLimitPx() string {
	if x != nil {
		return x.LimitPx
	}
	return ""
}

func (x *L4Order) GetSz() string {
	if x != nil {
		return x.Sz
	}
	return ""
}

func (x *L4Order) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *L4Order) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *L4Order) GetTriggerCondition() string {
	if x != nil {
		return x.TriggerCondition
	}
	return ""
}

func (x *L4Order) GetIsTrigger() bool {
	if x != nil {
		return x.IsTrigger
	}
	return false
}

func (x *L4Order) GetTriggerPx() string {
	if x != nil {
		return x.TriggerPx
	}
	return ""
}

func (x *L4Order) GetIsPositionTpsl() bool {
	if x != nil {
		return x.IsPositionTpsl
	}
	return false
}

func (x *L4Order) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *L4Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *L4Order) GetTif() string {
	if x != nil && x.Tif != nil {
		return *x.Tif
	}
	return ""
}

func (x *L4Order) GetCloid() string {
	if x != nil && x.Cloid != nil {
		return *x.Cloid
	}
	return ""
}

// Request parameters for TP/SL trigger order updates.
type TpslUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coins         []string               `protobuf:"bytes,1,rep,name=coins,proto3" json:"coins,omitempty"` // Empty means all perp coins
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TpslUpdatesRequest) Reset() {
	*x = TpslUpdatesRequest{}
	mi := &file_orderbook_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpslUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpslUpdatesRequest) ProtoMessage() {}

func (x *TpslUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpslUpdatesRequest.ProtoReflect.Descriptor instead.
func (*TpslUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{21}
}

func (x *TpslUpdatesRequest) GetCoins() []string {
	if x != nil {
		return x.Coins
	}
	return nil
}

// TP/SL trigger order update batch for one processed block.
type TpslUpdatesUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Diffs         []*TpslOrderDiff       `protobuf:"bytes,3,rep,name=diffs,proto3" json:"diffs,omitempty"`
	Snapshot      bool                   `protobuf:"varint,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // True when diffs carry currently-open trigger orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TpslUpdatesUpdate) Reset() {
	*x = TpslUpdatesUpdate{}
	mi := &file_orderbook_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpslUpdatesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpslUpdatesUpdate) ProtoMessage() {}

func (x *TpslUpdatesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpslUpdatesUpdate.ProtoReflect.Descriptor instead.
func (*TpslUpdatesUpdate) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{22}
}

func (x *TpslUpdatesUpdate) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TpslUpdatesUpdate) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TpslUpdatesUpdate) GetDiffs() []*TpslOrderDiff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

func (x *TpslUpdatesUpdate) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

// A trigger order add/remove event.
type TpslOrderDiff struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DiffType         TpslDiffType           `protobuf:"varint,1,opt,name=diff_type,json=diffType,proto3,enum=hyperliquid.TpslDiffType" json:"diff_type,omitempty"`
	Oid              uint64                 `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Coin             string                 `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`
	User             string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Side             string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"` // "A" (Ask) or "B" (Bid)
	TriggerPx        string                 `protobuf:"bytes,6,opt,name=trigger_px,json=triggerPx,proto3" json:"trigger_px,omitempty"`
	LimitPx          string                 `protobuf:"bytes,7,opt,name=limit_px,json=limitPx,proto3" json:"limit_px,omitempty"`
	Sz               string                 `protobuf:"bytes,8,opt,name=sz,proto3" json:"sz,omitempty"`
	TriggerCondition string                 `protobuf:"bytes,9,opt,name=trigger_condition,json=triggerCondition,proto3" json:"trigger_condition,omitempty"`
	OrderType        string                 `protobuf:"bytes,10,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	IsPositionTpsl   bool                   `protobuf:"varint,11,opt,name=is_position_tpsl,json=isPositionTpsl,proto3" json:"is_position_tpsl,omitempty"`
	ReduceOnly       bool                   `protobuf:"varint,12,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	Timestamp        uint64                 `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Order creation timestamp (milliseconds)
	Reason           string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`        // Present on remove; mirrors node status
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TpslOrderDiff) Reset() {
	*x = TpslOrderDiff{}
	mi := &file_orderbook_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpslOrderDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpslOrderDiff) ProtoMessage() {}

func (x *TpslOrderDiff) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpslOrderDiff.ProtoReflect.Descriptor instead.
func (*TpslOrderDiff) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{23}
}

func (x *TpslOrderDiff) GetDiffType() TpslDiffType {
	if x != nil {
		return x.DiffType
	}
	return TpslDiffType_TPSL_DIFF_TYPE_UNSPECIFIED
}

func (x *TpslOrderDiff) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *TpslOrderDiff) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *TpslOrderDiff) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TpslOrderDiff) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *TpslOrderDiff) GetTriggerPx() string {
	if x != nil {
		return x.TriggerPx
	}
	return ""
}

func (x *TpslOrderDiff) GetLimitPx() string {
	if x != nil {
		return x.LimitPx
	}
	return ""
}

func (x *TpslOrderDiff) GetSz() string {
	if x != nil {
		return x.Sz
	}
	return ""
}

func (x *TpslOrderDiff) GetTriggerCondition() string {
	if x != nil {
		return x.TriggerCondition
	}
	return ""
}

func (x *TpslOrderDiff) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *TpslOrderDiff) GetIsPositionTpsl() bool {
	if x != nil {
		return x.IsPositionTpsl
	}
	return false
}

func (x *TpslOrderDiff) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *TpslOrderDiff) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TpslOrderDiff) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_orderbook_proto protoreflect.FileDescriptor

const file_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x0forderbook.proto\x12\vhyperliquid\"\x9e\x01\n" +
	"\rL2BookRequest\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x19\n" +
	"\bn_levels\x18\x02 \x01(\rR\anLevels\x12!\n" +
	"\n" +
	"n_sig_figs\x18\x03 \x01(\rH\x00R\bnSigFigs\x88\x01\x01\x12\x1f\n" +
	"\bmantissa\x18\x04 \x01(\x04H\x01R\bmantissa\x88\x01\x01B\r\n" +
	"\v_n_sig_figsB\v\n" +
	"\t_mantissa\"\xad\x01\n" +
	"\fL2BookUpdate\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12(\n" +
	"\x04bids\x18\x04 \x03(\v2\x14.hyperliquid.L2LevelR\x04bids\x12(\n" +
	"\x04asks\x18\x05 \x03(\v2\x14.hyperliquid.L2LevelR\x04asks\"7\n" +
	"\aL2Level\x12\x0e\n" +
	"\x02px\x18\x01 \x01(\tR\x02px\x12\x0e\n" +
	"\x02sz\x18\x02 \x01(\tR\x02sz\x12\f\n" +
	"\x01n\x18\x03 \x01(\rR\x01n\"=\n" +
	"\rL2LevelPacked\x12\x0e\n" +
	"\x02px\x18\x01 \x01(\x06R\x02px\x12\x0e\n" +
	"\x02sz\x18\x02 \x01(\x06R\x02sz\x12\f\n" +
	"\x01n\x18\x03 \x01(\rR\x01n\"\xbf\x01\n" +
	"\x12L2BookPackedUpdate\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12.\n" +
	"\x04bids\x18\x04 \x03(\v2\x1a.hyperliquid.L2LevelPackedR\x04bids\x12.\n" +
	"\x04asks\x18\x05 \x03(\v2\x1a.hyperliquid.L2LevelPackedR\x04asks\"&\n" +
	"\x0eBboBookRequest\x12\x14\n" +
	"\x05coins\x18\x01 \x03(\tR\x05coins\"\xaa\x01\n" +
	"\rBboBookUpdate\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12&\n" +
	"\x03bid\x18\x04 \x01(\v2\x14.hyperliquid.L2LevelR\x03bid\x12&\n" +
	"\x03ask\x18\x05 \x01(\v2\x14.hyperliquid.L2LevelR\x03ask\"\xbc\x01\n" +
	"\x13BboBookPackedUpdate\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12,\n" +
	"\x03bid\x18\x04 \x01(\v2\x1a.hyperliquid.L2LevelPackedR\x03bid\x12,\n" +
	"\x03ask\x18\x05 \x01(\v2\x1a.hyperliquid.L2LevelPackedR\x03ask\"\xd8\x01\n" +
	"\x11L2BookDiffRequest\x12\x14\n" +
	"\x05coins\x18\x01 \x03(\tR\x05coins\x12\x19\n" +
	"\bn_levels\x18\x02 \x01(\rR\anLevels\x12!\n" +
	"\n" +
	"n_sig_figs\x18\x03 \x01(\rH\x00R\bnSigFigs\x88\x01\x01\x12\x1f\n" +
	"\bmantissa\x18\x04 \x01(\x04H\x01R\bmantissa\x88\x01\x01\x122\n" +
	"\x15skip_initial_snapshot\x18\x05 \x01(\bR\x13skipInitialSnapshotB\r\n" +
	"\v_n_sig_figsB\v\n" +
	"\t_mantissa\"\x89\x01\n" +
	"\x10L2BookDiffUpdate\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\bR\bsnapshot\x12-\n" +
	"\x05diffs\x18\x04 \x03(\v2\x17.hyperliquid.L2CoinDiffR\x05diffs\"\xbd\x01\n" +
	"\n" +
	"L2CoinDiff\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\bprev_seq\x18\x03 \x01(\x04R\aprevSeq\x12(\n" +
	"\x04bids\x18\x04 \x03(\v2\x14.hyperliquid.L2LevelR\x04bids\x12(\n" +
	"\x04asks\x18\x05 \x03(\v2\x14.hyperliquid.L2LevelR\x04asks\x12\x1a\n" +
	"\bsnapshot\x18\x06 \x01(\bR\bsnapshot\"#\n" +
	"\rL4BookRequest\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\"\x82\x01\n" +
	"\fL4BookUpdate\x129\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.hyperliquid.L4BookSnapshotH\x00R\bsnapshot\x12-\n" +
	"\x04diff\x18\x02 \x01(\v2\x17.hyperliquid.L4BookDiffH\x00R\x04diffB\b\n" +
	"\x06update\"\xa4\x01\n" +
	"\x0eL4BookSnapshot\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12(\n" +
	"\x04bids\x18\x04 \x03(\v2\x14.hyperliquid.L4OrderR\x04bids\x12(\n" +
	"\x04asks\x18\x05 \x03(\v2\x14.hyperliquid.L4OrderR\x04asks\"L\n" +
	"\n" +
	"L4BookDiff\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\x8c\x01\n" +
	"\x11L4BookBytesUpdate\x129\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.hyperliquid.L4BookSnapshotH\x00R\bsnapshot\x122\n" +
	"\x04diff\x18\x02 \x01(\v2\x1c.hyperliquid.L4BookBytesDiffH\x00R\x04diffB\b\n" +
	"\x06update\"Q\n" +
	"\x0fL4BookBytesDiff\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\",\n" +
	"\x14L4BookUpdatesRequest\x12\x14\n" +
	"\x05coins\x18\x01 \x03(\tR\x05coins\"\x8d\x01\n" +
	"\x13L4BookUpdatesUpdate\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12.\n" +
	"\x05diffs\x18\x03 \x03(\v2\x18.hyperliquid.L4OrderDiffR\x05diffs\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\"\xb6\x01\n" +
	"\vL4OrderDiff\x129\n" +
	"\tdiff_type\x18\x01 \x01(\x0e2\x1c.hyperliquid.L4OrderDiffTypeR\bdiffType\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\tR\x04coin\x12\x10\n" +
	"\x03oid\x18\x03 \x01(\x04R\x03oid\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x0e\n" +
	"\x02px\x18\x06 \x01(\tR\x02px\x12\x0e\n" +
	"\x02sz\x18\a \x01(\tR\x02sz\"\xb9\x03\n" +
	"\aL4Order\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\tR\x04coin\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x19\n" +
	"\blimit_px\x18\x04 \x01(\tR\alimitPx\x12\x0e\n" +
	"\x02sz\x18\x05 \x01(\tR\x02sz\x12\x10\n" +
	"\x03oid\x18\x06 \x01(\x04R\x03oid\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x12+\n" +
	"\x11trigger_condition\x18\b \x01(\tR\x10triggerCondition\x12\x1d\n" +
	"\n" +
	"is_trigger\x18\t \x01(\bR\tisTrigger\x12\x1d\n" +
	"\n" +
	"trigger_px\x18\n" +
	" \x01(\tR\ttriggerPx\x12(\n" +
	"\x10is_position_tpsl\x18\v \x01(\bR\x0eisPositionTpsl\x12\x1f\n" +
	"\vreduce_only\x18\f \x01(\bR\n" +
	"reduceOnly\x12\x1d\n" +
	"\n" +
	"order_type\x18\r \x01(\tR\torderType\x12\x15\n" +
	"\x03tif\x18\x0e \x01(\tH\x00R\x03tif\x88\x01\x01\x12\x19\n" +
	"\x05cloid\x18\x0f \x01(\tH\x01R\x05cloid\x88\x01\x01B\x06\n" +
	"\x04_tifB\b\n" +
	"\x06_cloid\"*\n" +
	"\x12TpslUpdatesRequest\x12\x14\n" +
	"\x05coins\x18\x01 \x03(\tR\x05coins\"\x8d\x01\n" +
	"\x11TpslUpdatesUpdate\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x04R\x04time\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x120\n" +
	"\x05diffs\x18\x03 \x03(\v2\x1a.hyperliquid.TpslOrderDiffR\x05diffs\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\"\xac\x03\n" +
	"\rTpslOrderDiff\x126\n" +
	"\tdiff_type\x18\x01 \x01(\x0e2\x19.hyperliquid.TpslDiffTypeR\bdiffType\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x04R\x03oid\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\tR\x04coin\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x1d\n" +
	"\n" +
	"trigger_px\x18\x06 \x01(\tR\ttriggerPx\x12\x19\n" +
	"\blimit_px\x18\a \x01(\tR\alimitPx\x12\x0e\n" +
	"\x02sz\x18\b \x01(\tR\x02sz\x12+\n" +
	"\x11trigger_condition\x18\t \x01(\tR\x10triggerCondition\x12\x1d\n" +
	"\n" +
	"order_type\x18\n" +
	" \x01(\tR\torderType\x12(\n" +
	"\x10is_position_tpsl\x18\v \x01(\bR\x0eisPositionTpsl\x12\x1f\n" +
	"\vreduce_only\x18\f \x01(\bR\n" +
	"reduceOnly\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason*\x8f\x01\n" +
	"\x0fL4OrderDiffType\x12\"\n" +
	"\x1eL4_ORDER_DIFF_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16L4_ORDER_DIFF_TYPE_NEW\x10\x01\x12\x1d\n" +
	"\x19L4_ORDER_DIFF_TYPE_UPDATE\x10\x02\x12\x1d\n" +
	"\x19L4_ORDER_DIFF_TYPE_REMOVE\x10\x03*a\n" +
	"\fTpslDiffType\x12\x1e\n" +
	"\x1aTPSL_DIFF_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TPSL_DIFF_TYPE_ADD\x10\x01\x12\x19\n" +
	"\x15TPSL_DIFF_TYPE_REMOVE\x10\x022\xfd\x05\n" +
	"\x12OrderBookStreaming\x12G\n" +
	"\fStreamL2Book\x12\x1a.hyperliquid.L2BookRequest\x1a\x19.hyperliquid.L2BookUpdate0\x01\x12G\n" +
	"\fStreamL4Book\x12\x1a.hyperliquid.L4BookRequest\x1a\x19.hyperliquid.L4BookUpdate0\x01\x12J\n" +
	"\rStreamBboBook\x12\x1b.hyperliquid.BboBookRequest\x1a\x1a.hyperliquid.BboBookUpdate0\x01\x12S\n" +
	"\x10StreamL2BookDiff\x12\x1e.hyperliquid.L2BookDiffRequest\x1a\x1d.hyperliquid.L2BookDiffUpdate0\x01\x12\\\n" +
	"\x13StreamL4BookUpdates\x12!.hyperliquid.L4BookUpdatesRequest\x1a .hyperliquid.L4BookUpdatesUpdate0\x01\x12V\n" +
	"\x11StreamTpslUpdates\x12\x1f.hyperliquid.TpslUpdatesRequest\x1a\x1e.hyperliquid.TpslUpdatesUpdate0\x01\x12S\n" +
	"\x12StreamL2BookPacked\x12\x1a.hyperliquid.L2BookRequest\x1a\x1f.hyperliquid.L2BookPackedUpdate0\x01\x12V\n" +
	"\x13StreamBboBookPacked\x12\x1b.hyperliquid.BboBookRequest\x1a .hyperliquid.BboBookPackedUpdate0\x01\x12Q\n" +
	"\x11StreamL4BookBytes\x12\x1a.hyperliquid.L4BookRequest\x1a\x1e.hyperliquid.L4BookBytesUpdate0\x01B?Z=github.com/quiknode-labs/hyperliquid-sdk/go/hyperliquid/protob\x06proto3"

var (
	file_orderbook_proto_rawDescOnce sync.Once
	file_orderbook_proto_rawDescData []byte
)

func file_orderbook_proto_rawDescGZIP() []byte {
	file_orderbook_proto_rawDescOnce.Do(func() {
		file_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)))
	})
	return file_orderbook_proto_rawDescData
}

var file_orderbook_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_orderbook_proto_goTypes = []any{
	(L4OrderDiffType)(0),         // 0: hyperliquid.L4OrderDiffType
	(TpslDiffType)(0),            // 1: hyperliquid.TpslDiffType
	(*L2BookRequest)(nil),        // 2: hyperliquid.L2BookRequest
	(*L2BookUpdate)(nil),         // 3: hyperliquid.L2BookUpdate
	(*L2Level)(nil),              // 4: hyperliquid.L2Level
	(*L2LevelPacked)(nil),        // 5: hyperliquid.L2LevelPacked
	(*L2BookPackedUpdate)(nil),   // 6: hyperliquid.L2BookPackedUpdate
	(*BboBookRequest)(nil),       // 7: hyperliquid.BboBookRequest
	(*BboBookUpdate)(nil),        // 8: hyperliquid.BboBookUpdate
	(*BboBookPackedUpdate)(nil),  // 9: hyperliquid.BboBookPackedUpdate
	(*L2BookDiffRequest)(nil),    // 10: hyperliquid.L2BookDiffRequest
	(*L2BookDiffUpdate)(nil),     // 11: hyperliquid.L2BookDiffUpdate
	(*L2CoinDiff)(nil),           // 12: hyperliquid.L2CoinDiff
	(*L4BookRequest)(nil),        // 13: hyperliquid.L4BookRequest
	(*L4BookUpdate)(nil),         // 14: hyperliquid.L4BookUpdate
	(*L4BookSnapshot)(nil),       // 15: hyperliquid.L4BookSnapshot
	(*L4BookDiff)(nil),           // 16: hyperliquid.L4BookDiff
	(*L4BookBytesUpdate)(nil),    // 17: hyperliquid.L4BookBytesUpdate
	(*L4BookBytesDiff)(nil),      // 18: hyperliquid.L4BookBytesDiff
	(*L4BookUpdatesRequest)(nil), // 19: hyperliquid.L4BookUpdatesRequest
	(*L4BookUpdatesUpdate)(nil),  // 20: hyperliquid.L4BookUpdatesUpdate
	(*L4OrderDiff)(nil),          // 21: hyperliquid.L4OrderDiff
	(*L4Order)(nil),              // 22: hyperliquid.L4Order
	(*TpslUpdatesRequest)(nil),   // 23: hyperliquid.TpslUpdatesRequest
	(*TpslUpdatesUpdate)(nil),    // 24: hyperliquid.TpslUpdatesUpdate
	(*TpslOrderDiff)(nil),        // 25: hyperliquid.TpslOrderDiff
}
var file_orderbook_proto_depIdxs = []int32{
	4,  // 0: hyperliquid.L2BookUpdate.bids:type_name -> hyperliquid.L2Level
	4,  // 1: hyperliquid.L2BookUpdate.asks:type_name -> hyperliquid.L2Level
	5,  // 2: hyperliquid.L2BookPackedUpdate.bids:type_name -> hyperliquid.L2LevelPacked
	5,  // 3: hyperliquid.L2BookPackedUpdate.asks:type_name -> hyperliquid.L2LevelPacked
	4,  // 4: hyperliquid.BboBookUpdate.bid:type_name -> hyperliquid.L2Level
	4,  // 5: hyperliquid.BboBookUpdate.ask:type_name -> hyperliquid.L2Level
	5,  // 6: hyperliquid.BboBookPackedUpdate.bid:type_name -> hyperliquid.L2LevelPacked
	5,  // 7: hyperliquid.BboBookPackedUpdate.ask:type_name -> hyperliquid.L2LevelPacked
	12, // 8: hyperliquid.L2BookDiffUpdate.diffs:type_name -> hyperliquid.L2CoinDiff
	4,  // 9: hyperliquid.L2CoinDiff.bids:type_name -> hyperliquid.L2Level
	4,  // 10: hyperliquid.L2CoinDiff.asks:type_name -> hyperliquid.L2Level
	15, // 11: hyperliquid.L4BookUpdate.snapshot:type_name -> hyperliquid.L4BookSnapshot
	16, // 12: hyperliquid.L4BookUpdate.diff:type_name -> hyperliquid.L4BookDiff
	22, // 13: hyperliquid.L4BookSnapshot.bids:type_name -> hyperliquid.L4Order
	22, // 14: hyperliquid.L4BookSnapshot.asks:type_name -> hyperliquid.L4Order
	15, // 15: hyperliquid.L4BookBytesUpdate.snapshot:type_name -> hyperliquid.L4BookSnapshot
	18, // 16: hyperliquid.L4BookBytesUpdate.diff:type_name -> hyperliquid.L4BookBytesDiff
	21, // 17: hyperliquid.L4BookUpdatesUpdate.diffs:type_name -> hyperliquid.L4OrderDiff
	0,  // 18: hyperliquid.L4OrderDiff.diff_type:type_name -> hyperliquid.L4OrderDiffType
	25, // 19: hyperliquid.TpslUpdatesUpdate.diffs:type_name -> hyperliquid.TpslOrderDiff
	1,  // 20: hyperliquid.TpslOrderDiff.diff_type:type_name -> hyperliquid.TpslDiffType
	2,  // 21: hyperliquid.OrderBookStreaming.StreamL2Book:input_type -> hyperliquid.L2BookRequest
	13, // 22: hyperliquid.OrderBookStreaming.StreamL4Book:input_type -> hyperliquid.L4BookRequest
	7,  // 23: hyperliquid.OrderBookStreaming.StreamBboBook:input_type -> hyperliquid.BboBookRequest
	10, // 24: hyperliquid.OrderBookStreaming.StreamL2BookDiff:input_type -> hyperliquid.L2BookDiffRequest
	19, // 25: hyperliquid.OrderBookStreaming.StreamL4BookUpdates:input_type -> hyperliquid.L4BookUpdatesRequest
	23, // 26: hyperliquid.OrderBookStreaming.StreamTpslUpdates:input_type -> hyperliquid.TpslUpdatesRequest
	2,  // 27: hyperliquid.OrderBookStreaming.StreamL2BookPacked:input_type -> hyperliquid.L2BookRequest
	7,  // 28: hyperliquid.OrderBookStreaming.StreamBboBookPacked:input_type -> hyperliquid.BboBookRequest
	13, // 29: hyperliquid.OrderBookStreaming.StreamL4BookBytes:input_type -> hyperliquid.L4BookRequest
	3,  // 30: hyperliquid.OrderBookStreaming.StreamL2Book:output_type -> hyperliquid.L2BookUpdate
	14, // 31: hyperliquid.OrderBookStreaming.StreamL4Book:output_type -> hyperliquid.L4BookUpdate
	8,  // 32: hyperliquid.OrderBookStreaming.StreamBboBook:output_type -> hyperliquid.BboBookUpdate
	11, // 33: hyperliquid.OrderBookStreaming.StreamL2BookDiff:output_type -> hyperliquid.L2BookDiffUpdate
	20, // 34: hyperliquid.OrderBookStreaming.StreamL4BookUpdates:output_type -> hyperliquid.L4BookUpdatesUpdate
	24, // 35: hyperliquid.OrderBookStreaming.StreamTpslUpdates:output_type -> hyperliquid.TpslUpdatesUpdate
	6,  // 36: hyperliquid.OrderBookStreaming.StreamL2BookPacked:output_type -> hyperliquid.L2BookPackedUpdate
	9,  // 37: hyperliquid.OrderBookStreaming.StreamBboBookPacked:output_type -> hyperliquid.BboBookPackedUpdate
	17, // 38: hyperliquid.OrderBookStreaming.StreamL4BookBytes:output_type -> hyperliquid.L4BookBytesUpdate
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_orderbook_proto_init() }
func file_orderbook_proto_init() {
	if File_orderbook_proto != nil {
		return
	}
	file_orderbook_proto_msgTypes[0].OneofWrappers = []any{}
	file_orderbook_proto_msgTypes[8].OneofWrappers = []any{}
	file_orderbook_proto_msgTypes[12].OneofWrappers = []any{
		(*L4BookUpdate_Snapshot)(nil),
		(*L4BookUpdate_Diff)(nil),
	}
	file_orderbook_proto_msgTypes[15].OneofWrappers = []any{
		(*L4BookBytesUpdate_Snapshot)(nil),
		(*L4BookBytesUpdate_Diff)(nil),
	}
	file_orderbook_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderbook_proto_goTypes,
		DependencyIndexes: file_orderbook_proto_depIdxs,
		EnumInfos:         file_orderbook_proto_enumTypes,
		MessageInfos:      file_orderbook_proto_msgTypes,
	}.Build()
	File_orderbook_proto = out.File
	file_orderbook_proto_goTypes = nil
	file_orderbook_proto_depIdxs = nil
}
