// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: streaming.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Data Types ---
type StreamType int32

const (
	StreamType_UNKNOWN        StreamType = 0
	StreamType_TRADES         StreamType = 1
	StreamType_ORDERS         StreamType = 2
	StreamType_BOOK_UPDATES   StreamType = 3
	StreamType_TWAP           StreamType = 4
	StreamType_EVENTS         StreamType = 5
	StreamType_BLOCKS         StreamType = 6
	StreamType_WRITER_ACTIONS StreamType = 7
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TRADES",
		2: "ORDERS",
		3: "BOOK_UPDATES",
		4: "TWAP",
		5: "EVENTS",
		6: "BLOCKS",
		7: "WRITER_ACTIONS",
	}
	StreamType_value = map[string]int32{
		"UNKNOWN":        0,
		"TRADES":         1,
		"ORDERS":         2,
		"BOOK_UPDATES":   3,
		"TWAP":           4,
		"EVENTS":         5,
		"BLOCKS":         6,
		"WRITER_ACTIONS": 7,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_streaming_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_streaming_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

// --- Requests ---
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*SubscribeRequest_Subscribe
	//	*SubscribeRequest_Ping
	Request       isSubscribeRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetRequest() isSubscribeRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SubscribeRequest) GetSubscribe() *StreamSubscribe {
	if x != nil {
		if x, ok := x.Request.(*SubscribeRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *SubscribeRequest) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Request.(*SubscribeRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isSubscribeRequest_Request interface {
	isSubscribeRequest_Request()
}

type SubscribeRequest_Subscribe struct {
	Subscribe *StreamSubscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SubscribeRequest_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*SubscribeRequest_Subscribe) isSubscribeRequest_Request() {}

func (*SubscribeRequest_Ping) isSubscribeRequest_Request() {}

type StreamSubscribe struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StreamType StreamType             `protobuf:"varint,1,opt,name=stream_type,json=streamType,proto3,enum=hyperliquid.StreamType" json:"stream_type,omitempty"`
	// Generic filters - field name to allowed values
	// Recursively searches each event for matching field/value pairs
	// Example: {"coin": ["ETH", "BTC"], "user": ["0x123..."], "type": ["deposit"]}
	Filters map[string]*FilterValues `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional name for this filter
	// Allows multiple independent filters per stream (OR logic)
	FilterName    string `protobuf:"bytes,4,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSubscribe) Reset() {
	*x = StreamSubscribe{}
	mi := &file_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSubscribe) ProtoMessage() {}

func (x *StreamSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSubscribe.ProtoReflect.Descriptor instead.
func (*StreamSubscribe) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *StreamSubscribe) GetStreamType() StreamType {
	if x != nil {
		return x.StreamType
	}
	return StreamType_UNKNOWN
}

func (x *StreamSubscribe) GetFilters() map[string]*FilterValues {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *StreamSubscribe) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

// Container for filter values
type FilterValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterValues) Reset() {
	*x = FilterValues{}
	mi := &file_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterValues) ProtoMessage() {}

func (x *FilterValues) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterValues.ProtoReflect.Descriptor instead.
func (*FilterValues) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *FilterValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// --- Responses ---
type SubscribeUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*SubscribeUpdate_Data
	//	*SubscribeUpdate_Pong
	Update        isSubscribeUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUpdate) Reset() {
	*x = SubscribeUpdate{}
	mi := &file_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUpdate) ProtoMessage() {}

func (x *SubscribeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUpdate.ProtoReflect.Descriptor instead.
func (*SubscribeUpdate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeUpdate) GetUpdate() isSubscribeUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *SubscribeUpdate) GetData() *StreamResponse {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *SubscribeUpdate) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isSubscribeUpdate_Update interface {
	isSubscribeUpdate_Update()
}

type SubscribeUpdate_Data struct {
	Data *StreamResponse `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type SubscribeUpdate_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

func (*SubscribeUpdate_Data) isSubscribeUpdate_Update() {}

func (*SubscribeUpdate_Pong) isSubscribeUpdate_Update() {}

type StreamResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Timestamp   uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Server ingress timestamp
	// Raw JSON data from the file (Exact replica of source)
	Data          string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *StreamResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *StreamResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataJson      string                 `protobuf:"bytes,1,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *Block) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_streaming_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{8}
}

func (x *Timestamp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_streaming_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_streaming_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_streaming_proto protoreflect.FileDescriptor

const file_streaming_proto_rawDesc = "" +
	"\n" +
	"\x0fstreaming.proto\x12\vhyperliquid\"\x8a\x01\n" +
	"\x10SubscribeRequest\x12<\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1c.hyperliquid.StreamSubscribeH\x00R\tsubscribe\x12'\n" +
	"\x04ping\x18\x03 \x01(\v2\x11.hyperliquid.PingH\x00R\x04pingB\t\n" +
	"\arequestJ\x04\b\x02\x10\x03\"\x88\x02\n" +
	"\x0fStreamSubscribe\x128\n" +
	"\vstream_type\x18\x01 \x01(\x0e2\x17.hyperliquid.StreamTypeR\n" +
	"streamType\x12C\n" +
	"\afilters\x18\x03 \x03(\v2).hyperliquid.StreamSubscribe.FiltersEntryR\afilters\x12\x1f\n" +
	"\vfilter_name\x18\x04 \x01(\tR\n" +
	"filterName\x1aU\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.hyperliquid.FilterValuesR\x05value:\x028\x01\"&\n" +
	"\fFilterValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"w\n" +
	"\x0fSubscribeUpdate\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.hyperliquid.StreamResponseH\x00R\x04data\x12'\n" +
	"\x04pong\x18\x02 \x01(\v2\x11.hyperliquid.PongH\x00R\x04pongB\b\n" +
	"\x06update\"e\n" +
	"\x0eStreamResponse\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"$\n" +
	"\x05Block\x12\x1b\n" +
	"\tdata_json\x18\x01 \x01(\tR\bdataJson\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\")\n" +
	"\tTimestamp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count*y\n" +
	"\n" +
	"StreamType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06TRADES\x10\x01\x12\n" +
	"\n" +
	"\x06ORDERS\x10\x02\x12\x10\n" +
	"\fBOOK_UPDATES\x10\x03\x12\b\n" +
	"\x04TWAP\x10\x04\x12\n" +
	"\n" +
	"\x06EVENTS\x10\x05\x12\n" +
	"\n" +
	"\x06BLOCKS\x10\x06\x12\x12\n" +
	"\x0eWRITER_ACTIONS\x10\a2\x97\x01\n" +
	"\tStreaming\x12M\n" +
	"\n" +
	"StreamData\x12\x1d.hyperliquid.SubscribeRequest\x1a\x1c.hyperliquid.SubscribeUpdate(\x010\x01\x12;\n" +
	"\x04Ping\x12\x18.hyperliquid.PingRequest\x1a\x19.hyperliquid.PingResponse2N\n" +
	"\x0eBlockStreaming\x12<\n" +
	"\fStreamBlocks\x12\x16.hyperliquid.Timestamp\x1a\x12.hyperliquid.Block0\x01B?Z=github.com/quiknode-labs/hyperliquid-sdk/go/hyperliquid/protob\x06proto3"

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData []byte
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)))
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_streaming_proto_goTypes = []any{
	(StreamType)(0),          // 0: hyperliquid.StreamType
	(*SubscribeRequest)(nil), // 1: hyperliquid.SubscribeRequest
	(*StreamSubscribe)(nil),  // 2: hyperliquid.StreamSubscribe
	(*FilterValues)(nil),     // 3: hyperliquid.FilterValues
	(*Ping)(nil),             // 4: hyperliquid.Ping
	(*SubscribeUpdate)(nil),  // 5: hyperliquid.SubscribeUpdate
	(*StreamResponse)(nil),   // 6: hyperliquid.StreamResponse
	(*Block)(nil),            // 7: hyperliquid.Block
	(*Pong)(nil),             // 8: hyperliquid.Pong
	(*Timestamp)(nil),        // 9: hyperliquid.Timestamp
	(*PingRequest)(nil),      // 10: hyperliquid.PingRequest
	(*PingResponse)(nil),     // 11: hyperliquid.PingResponse
	nil,                      // 12: hyperliquid.StreamSubscribe.FiltersEntry
}
var file_streaming_proto_depIdxs = []int32{
	2,  // 0: hyperliquid.SubscribeRequest.subscribe:type_name -> hyperliquid.StreamSubscribe
	4,  // 1: hyperliquid.SubscribeRequest.ping:type_name -> hyperliquid.Ping
	0,  // 2: hyperliquid.StreamSubscribe.stream_type:type_name -> hyperliquid.StreamType
	12, // 3: hyperliquid.StreamSubscribe.filters:type_name -> hyperliquid.StreamSubscribe.FiltersEntry
	6,  // 4: hyperliquid.SubscribeUpdate.data:type_name -> hyperliquid.StreamResponse
	8,  // 5: hyperliquid.SubscribeUpdate.pong:type_name -> hyperliquid.Pong
	3,  // 6: hyperliquid.StreamSubscribe.FiltersEntry.value:type_name -> hyperliquid.FilterValues
	1,  // 7: hyperliquid.Streaming.StreamData:input_type -> hyperliquid.SubscribeRequest
	10, // 8: hyperliquid.Streaming.Ping:input_type -> hyperliquid.PingRequest
	9,  // 9: hyperliquid.BlockStreaming.StreamBlocks:input_type -> hyperliquid.Timestamp
	5,  // 10: hyperliquid.Streaming.StreamData:output_type -> hyperliquid.SubscribeUpdate
	11, // 11: hyperliquid.Streaming.Ping:output_type -> hyperliquid.PingResponse
	7,  // 12: hyperliquid.BlockStreaming.StreamBlocks:output_type -> hyperliquid.Block
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	file_streaming_proto_msgTypes[0].OneofWrappers = []any{
		(*SubscribeRequest_Subscribe)(nil),
		(*SubscribeRequest_Ping)(nil),
	}
	file_streaming_proto_msgTypes[4].OneofWrappers = []any{
		(*SubscribeUpdate_Data)(nil),
		(*SubscribeUpdate_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		EnumInfos:         file_streaming_proto_enumTypes,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
