// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: streaming.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Streaming_StreamData_FullMethodName = "/hyperliquid.Streaming/StreamData"
	Streaming_Ping_FullMethodName       = "/hyperliquid.Streaming/Ping"
)

// StreamingClient is the client API for Streaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingClient interface {
	// Bi-directional streaming
	StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, SubscribeUpdate], error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type streamingClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingClient(cc grpc.ClientConnInterface) StreamingClient {
	return &streamingClient{cc}
}

func (c *streamingClient) StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, SubscribeUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Streaming_ServiceDesc.Streams[0], Streaming_StreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Streaming_StreamDataClient = grpc.BidiStreamingClient[SubscribeRequest, SubscribeUpdate]

func (c *streamingClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Streaming_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingServer is the server API for Streaming service.
// All implementations must embed UnimplementedStreamingServer
// for forward compatibility.
type StreamingServer interface {
	// Bi-directional streaming
	StreamData(grpc.BidiStreamingServer[SubscribeRequest, SubscribeUpdate]) error
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedStreamingServer()
}

// UnimplementedStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServer struct{}

func (UnimplementedStreamingServer) StreamData(grpc.BidiStreamingServer[SubscribeRequest, SubscribeUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedStreamingServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStreamingServer) mustEmbedUnimplementedStreamingServer() {}
func (UnimplementedStreamingServer) testEmbeddedByValue()                   {}

// UnsafeStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServer will
// result in compilation errors.
type UnsafeStreamingServer interface {
	mustEmbedUnimplementedStreamingServer()
}

func RegisterStreamingServer(s grpc.ServiceRegistrar, srv StreamingServer) {
	// If the following call pancis, it indicates UnimplementedStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Streaming_ServiceDesc, srv)
}

func _Streaming_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServer).StreamData(&grpc.GenericServerStream[SubscribeRequest, SubscribeUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Streaming_StreamDataServer = grpc.BidiStreamingServer[SubscribeRequest, SubscribeUpdate]

func _Streaming_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Streaming_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Streaming_ServiceDesc is the grpc.ServiceDesc for Streaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Streaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperliquid.Streaming",
	HandlerType: (*StreamingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Streaming_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _Streaming_StreamData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "streaming.proto",
}

const (
	BlockStreaming_StreamBlocks_FullMethodName = "/hyperliquid.BlockStreaming/StreamBlocks"
)

// BlockStreamingClient is the client API for BlockStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockStreamingClient interface {
	// Stream replica_cmds (raw blocks)
	StreamBlocks(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
}

type blockStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockStreamingClient(cc grpc.ClientConnInterface) BlockStreamingClient {
	return &blockStreamingClient{cc}
}

func (c *blockStreamingClient) StreamBlocks(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockStreaming_ServiceDesc.Streams[0], BlockStreaming_StreamBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Timestamp, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreaming_StreamBlocksClient = grpc.ServerStreamingClient[Block]

// BlockStreamingServer is the server API for BlockStreaming service.
// All implementations must embed UnimplementedBlockStreamingServer
// for forward compatibility.
type BlockStreamingServer interface {
	// Stream replica_cmds (raw blocks)
	StreamBlocks(*Timestamp, grpc.ServerStreamingServer[Block]) error
	mustEmbedUnimplementedBlockStreamingServer()
}

// UnimplementedBlockStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockStreamingServer struct{}

func (UnimplementedBlockStreamingServer) StreamBlocks(*Timestamp, grpc.ServerStreamingServer[Block]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBlocks not implemented")
}
func (UnimplementedBlockStreamingServer) mustEmbedUnimplementedBlockStreamingServer() {}
func (UnimplementedBlockStreamingServer) testEmbeddedByValue()                        {}

// UnsafeBlockStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockStreamingServer will
// result in compilation errors.
type UnsafeBlockStreamingServer interface {
	mustEmbedUnimplementedBlockStreamingServer()
}

func RegisterBlockStreamingServer(s grpc.ServiceRegistrar, srv BlockStreamingServer) {
	// If the following call pancis, it indicates UnimplementedBlockStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockStreaming_ServiceDesc, srv)
}

func _BlockStreaming_StreamBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Timestamp)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockStreamingServer).StreamBlocks(m, &grpc.GenericServerStream[Timestamp, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreaming_StreamBlocksServer = grpc.ServerStreamingServer[Block]

// BlockStreaming_ServiceDesc is the grpc.ServiceDesc for BlockStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperliquid.BlockStreaming",
	HandlerType: (*BlockStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBlocks",
			Handler:       _BlockStreaming_StreamBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
